### Practical 24

### Demonstrate naive based algorithm on 'Wine Dataset'  and compare the accuracy achieved with that of logistic regression, decision tree and random forest model

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
# Importing the dataset

from sklearn.datasets import load_wine
import sklearn.datasets as data
wine_data = load_wine()
dataset = pd.DataFrame(wine_data.data)
dataset.head()

0     1     2     3      4     5     6     7     8     9     10    11  \
0  14.23  1.71  2.43  15.6  127.0  2.80  3.06  0.28  2.29  5.64  1.04  3.92   
1  13.20  1.78  2.14  11.2  100.0  2.65  2.76  0.26  1.28  4.38  1.05  3.40   
2  13.16  2.36  2.67  18.6  101.0  2.80  3.24  0.30  2.81  5.68  1.03  3.17   
3  14.37  1.95  2.50  16.8  113.0  3.85  3.49  0.24  2.18  7.80  0.86  3.45   
4  13.24  2.59  2.87  21.0  118.0  2.80  2.69  0.39  1.82  4.32  1.04  2.93   

       12  
0  1065.0  
1  1050.0  
2  1185.0  
3  1480.0  
4   735.0

In [17]:
print(dataset.columns.values) #printing column names

[ 0  1  2  3  4  5  6  7  8  9 10 11 12]


In [4]:
# Independent Features (Predictor or Data) - Age and Salary column all rows
x = dataset.iloc[:,:-1].values

# Dependent feature (Target)
y = wine_data.target

In [5]:
# Feature scaling
from sklearn.preprocessing import StandardScaler

sc = StandardScaler()1
x = sc.fit_transform(x)v 

In [6]:
# Splitting the dataset into the training set and test set

from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x,y, test_size = 0.25, random_state=0)

In [7]:
# Fitting Naive Bayes to the training set

# Here we have used the GaussianNB classifier to fit it to the training dataset.
# most important code of the complete code
from sklearn.naive_bayes import GaussianNB

classifier = GaussianNB()

classifier.fit(x_train, y_train)

GaussianNB()

In [8]:
# Predicting the test set results

y_pred = classifier.predict(x_test)
y_pred

array([0, 2, 0, 0, 1, 1, 0, 2, 1, 1, 2, 2, 0, 0, 2, 1, 0, 0, 2, 0, 0, 0,
       0, 1, 1, 1, 1, 1, 1, 2, 0, 0, 1, 0, 0, 0, 2, 1, 1, 2, 0, 0, 1, 1,
       1])

In [9]:
# Making the confusioin Matrix

from sklearn.metrics import confusion_matrix

cm = confusion_matrix(y_test, y_pred)
cm

array([[16,  0,  0],
       [ 3, 17,  1],
       [ 0,  0,  8]], dtype=int64)

In [10]:
from sklearn.metrics import classification_report
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.84      1.00      0.91        16
           1       1.00      0.81      0.89        21
           2       0.89      1.00      0.94         8

    accuracy                           0.91        45
   macro avg       0.91      0.94      0.92        45
weighted avg       0.92      0.91      0.91        45



In [11]:
from sklearn import metrics
print("Gaussian Naive Bayes Model Accuracy: ", metrics.accuracy_score(y_test, y_pred)*100,"%")

Gaussian Naive Bayes Model Accuracy:  91.11111111111111 %


### Conclusion

In K-NN the accuracy is 95% and in Logistic Regression the accuracy is 92.5%
So we can conclude that for this dataset K-NN algorithm is prefered.