# Practical 23

### Demonstrate naive based algorithm on 'User_Data'  compare the accuracy achieved with that of logistic regression, decision tree and random forest model

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
# Importing the dataset

dataset = pd.read_csv("D:/ML Dataset/User_Data.csv")

# Independent Features (Predictor or Data) - Age and Salary column all rows

x = dataset.iloc[:,[2,3]].values

# Dependent feature (Target)

y = dataset.iloc[:,4].values

In [3]:
# Splitting the dataset into the training set and test set

from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x,y, test_size = 0.25, random_state=6)

In [10]:
# Feature scaling

from sklearn.preprocessing import StandardScaler

sc = StandardScaler()

x_train = sc.fit_transform(x_train)

x_test = sc.transform(x_test)

x_test[0:5]

array([[-0.7085005 ,  1.16500551],
       [-0.89693149, -0.30554843],
       [-0.52006952, -1.56164659],
       [-0.23742304, -0.76509654],
       [-1.36800895, -1.25528118]])

In [5]:
# Fitting Naive Bayes to the training set

# Here we have used the GaussianNB classifier to fit it to the training dataset.
# most important code of the complete code
from sklearn.naive_bayes import GaussianNB

classifier = GaussianNB()

classifier.fit(x_train, y_train)

GaussianNB()

In [6]:
# Predicting the test set results

y_pred = classifier.predict(x_test)
y_pred

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0,
       0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0,
       0, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0,
       1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0], dtype=int64)

In [7]:
# Making the confusioin Matrix

from sklearn.metrics import confusion_matrix

cm = confusion_matrix(y_test, y_pred)
cm

array([[59,  3],
       [ 6, 32]], dtype=int64)

In [8]:
from sklearn.metrics import classification_report
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.91      0.95      0.93        62
           1       0.91      0.84      0.88        38

    accuracy                           0.91       100
   macro avg       0.91      0.90      0.90       100
weighted avg       0.91      0.91      0.91       100



In [11]:
from sklearn import metrics
print("Gaussian Naive Bayes Model Accuracy: ", metrics.accuracy_score(y_test, y_pred)*100,"%")

Gaussian Naive Bayes Model Accuracy:  91.0 %


### Conclusion

In K-NN the accuracy is 95% and in Logistic Regression the accuracy is 92.5%
So we can conclude that for this dataset K-NN algorithm is prefered.