# Practical 19

### For Teleco Churn DataSet Train a model using KNN Classifier and select K neighbours to find out optimal value K. Also find accuracy score for each Neighbour.

In [1]:
import numpy as np
import pandas as pd
from matplotlib import pyplot
import matplotlib.pyplot as plt
from sklearn import preprocessing

In [2]:
# As you can see, there are 12 columns, namely as region, tenure, age, marital, address, income
# ed, employ, retire, gender, reside, and custcat.
# we have a target column, 'custcat' categorizes the customers into four groups which are 1,2,3,4

In [3]:
dataset = pd.read_csv("D:/ML Dataset/Telecustomers.csv")
dataset.head(5)

region  tenure  age  marital  address  income  ed  employ  retire  gender  \
0       2      13   44        1        9    64.0   4       5     0.0       0   
1       3      11   33        1        7   136.0   5       5     0.0       0   
2       3      68   52        1       24   116.0   1      29     0.0       1   
3       2      33   33        0       12    33.0   2       0     0.0       1   
4       2      23   30        1        9    30.0   1       2     0.0       0   

   reside  custcat  
0       2        1  
1       6        4  
2       2        3  
3       1        1  
4       4        3

In [26]:
dataset.describe()

region       tenure          age      marital      address  \
count  1000.0000  1000.000000  1000.000000  1000.000000  1000.000000   
mean      2.0220    35.526000    41.684000     0.495000    11.551000   
std       0.8162    21.359812    12.558816     0.500225    10.086681   
min       1.0000     1.000000    18.000000     0.000000     0.000000   
25%       1.0000    17.000000    32.000000     0.000000     3.000000   
50%       2.0000    34.000000    40.000000     0.000000     9.000000   
75%       3.0000    54.000000    51.000000     1.000000    18.000000   
max       3.0000    72.000000    77.000000     1.000000    55.000000   

            income           ed       employ       retire       gender  \
count  1000.000000  1000.000000  1000.000000  1000.000000  1000.000000   
mean     77.535000     2.671000    10.987000     0.047000     0.517000   
std     107.044165     1.222397    10.082087     0.211745     0.499961   
min       9.000000     1.000000     0.000000     0.000000     0.000000   
25%      29.000000     2.000000     3.000000     0.000000     0.000000   
50%      47.000000     3.000000     8.000000     0.000000     1.000000   
75%      83.000000     4.000000    17.000000     0.000000     1.000000   
max    1668.000000     5.000000    47.000000     1.000000     1.000000   

            reside      custcat  
count  1000.000000  1000.000000  
mean      2.331000     2.487000  
std       1.435793     1.120306  
min       1.000000     1.000000  
25%       1.000000     1.000000  
50%       2.000000     3.000000  
75%       3.000000     3.000000  
max       8.000000     4.000000

In [5]:
dataset['custcat'].value_counts()

3    281
1    266
4    236
2    217
Name: custcat, dtype: int64

In [6]:
dataset.columns

Index(['region', 'tenure', 'age', 'marital', 'address', 'income', 'ed',
       'employ', 'retire', 'gender', 'reside', 'custcat'],
      dtype='object')

In [27]:
# we collect all independent data features into the X data-frame and target field in 

X = dataset[['region', 'tenure', 'age', 'marital', 'address', 'income','ed','employ','retire','gender']]
print('Independent Variable :','\n',X[0:5])

y = dataset['custcat'].values
print('Dependent Variable :','\n',y[0:5])


Independent Variable : 
    region  tenure  age  marital  address  income  ed  employ  retire  gender
0       2      13   44        1        9    64.0   4       5     0.0       0
1       3      11   33        1        7   136.0   5       5     0.0       0
2       3      68   52        1       24   116.0   1      29     0.0       1
3       2      33   33        0       12    33.0   2       0     0.0       1
4       2      23   30        1        9    30.0   1       2     0.0       0
Dependent Variable : 
 [1 4 3 1 3]


In [28]:
# Now we manipulate the data and normalize it.
# Normalisizing value of the Independent Variable set
# This is to save memory and the required steps to do the same.
# Here we are using anonymous objects
#Anonymous objects - without creating defined objects they are used to perform as objects

from sklearn import preprocessing
X = preprocessing.StandardScaler().fit(X).transform(X.astype(float))

In [29]:
# Normalized values of Independent variable set X

X[0:5]

array([[-0.02696767, -1.055125  ,  0.18450456,  1.0100505 , -0.25303431,
        -0.12650641,  1.0877526 , -0.5941226 , -0.22207644, -1.03459817],
       [ 1.19883553, -1.14880563, -0.69181243,  1.0100505 , -0.4514148 ,
         0.54644972,  1.9062271 , -0.5941226 , -0.22207644, -1.03459817],
       [ 1.19883553,  1.52109247,  0.82182601,  1.0100505 ,  1.23481934,
         0.35951747, -1.36767088,  1.78752803, -0.22207644,  0.96655883],
       [-0.02696767, -0.11831864, -0.69181243, -0.9900495 ,  0.04453642,
        -0.41625141, -0.54919639, -1.09029981, -0.22207644,  0.96655883],
       [-0.02696767, -0.58672182, -0.93080797,  1.0100505 , -0.25303431,
        -0.44429125, -1.36767088, -0.89182893, -0.22207644, -1.03459817]])

In [10]:
# Now splitting the data, we take 0.8% data for training and remaining for test size.

from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 4)

In [30]:
# We import the classifier model from the sklearn library and fit the model by initializing K=4
# So we have achived an accuracy of 0.32 here.

from sklearn.neighbors import KNeighborsClassifier
from sklearn import metrics

# Train Model and Predict
# checking for K=4
# p is the lambda hyper parameter
# Only fitting the data not transforming it because it will change the 

k=4
knnClassifier = KNeighborsClassifier(n_neighbors = k, metric = 'minkowski', p=2). fit(X_train,y_train)
Pred_y = knnClassifier.predict(X_test)
print("Accuracy of model at K=4 is", metrics. accuracy_score(y_test,Pred_y))

Accuracy of model at K=4 is 0.325


In [31]:
# Now let us try to improve the odel accuracy and find out the optimal k value.

# To find the best value of k we take some range of values of k and
# then we will calculate the mean error rate of all these Ks.

# Let us take K = 5

k = 5
knnClassifier = KNeighborsClassifier(n_neighbors = k, metric = 'minkowski', p=2). fit(X_train,y_train)
Pred_y = knnClassifier.predict(X_test)
print("Accuracy of model at K=5 is", metrics. accuracy_score(y_test,Pred_y))

Accuracy of model at K=5 is 0.335


In [32]:
# Let us take K = 6

k = 6
knnClassifier = KNeighborsClassifier(n_neighbors = k, metric = 'minkowski', p=2). fit(X_train,y_train)
Pred_y = knnClassifier.predict(X_test)
print("Accuracy of model at K=6 is", metrics. accuracy_score(y_test,Pred_y))

Accuracy of model at K=6 is 0.32


In [33]:
# Let us take K = 7

k = 7
knnClassifier = KNeighborsClassifier(n_neighbors = k, metric = 'minkowski', p=2). fit(X_train,y_train)
Pred_y = knnClassifier.predict(X_test)
print("Accuracy of model at K=7 is", metrics. accuracy_score(y_test,Pred_y))

Accuracy of model at K=7 is 0.35


In [34]:
# Let us take K = 8

k = 8
knnClassifier = KNeighborsClassifier(n_neighbors = k, metric = 'minkowski', p=2). fit(X_train,y_train)
Pred_y = knnClassifier.predict(X_test)
print("Accuracy of model at K=8 is", metrics. accuracy_score(y_test,Pred_y))

Accuracy of model at K=8 is 0.345


In [35]:
# Let us take K = 16

k = 16
knnClassifier = KNeighborsClassifier(n_neighbors = k, metric = 'minkowski', p=2). fit(X_train,y_train)
Pred_y = knnClassifier.predict(X_test)
print("Accuracy of model at K=16 is", metrics. accuracy_score(y_test,Pred_y))

Accuracy of model at K=16 is 0.35


In [36]:
# Let us take K = 30

k = 30
knnClassifier = KNeighborsClassifier(n_neighbors = k, metric = 'minkowski', p=2). fit(X_train,y_train)
Pred_y = knnClassifier.predict(X_test)
print("Accuracy of model at K=30 is", metrics. accuracy_score(y_test,Pred_y))

Accuracy of model at K=30 is 0.365


In [37]:
# Let us take K = 35

k = 40
knnClassifier = KNeighborsClassifier(n_neighbors = k, metric = 'minkowski', p=2). fit(X_train,y_train)
Pred_y = knnClassifier.predict(X_test)
print("Accuracy of model at K=40 is", metrics. accuracy_score(y_test,Pred_y))

Accuracy of model at K=40 is 0.375


In [38]:
# To find optima 'K' derive a plot between error rate and K denoting values in a defined
# Then choose the K value as having a minimum error rate.
# In general optimal value of 'K' : sqrt(N)
# To get an upper limit to check for 'sqrt(N)+10'
                #sqrt(N)
                

In [43]:
from sklearn import metrics
k=33
knnClassifier = KNeighborsClassifier(n_neighbors = k, metric = 'minkowski', p=2). fit(X_train,y_train)
Pred_y = knnClassifier.predict(X_test)
print("Accuracy of model at K=33 is", metrics. accuracy_score(y_test,Pred_y))
confusion_matrix = metrics.confusion_matrix(y_test, Pred_y)
print('Confusion Matrix :','\n',confusion_matrix)
print('Accuracy Score :',metrics.accuracy_score(y_test, Pred_y)*100,'%')

Accuracy of model at K=33 is 0.375
Confusion Matrix : 
 [[29  3 12  7]
 [ 7 13 14 10]
 [21  6 21  6]
 [20  7 12 12]]
Accuracy Score : 37.5 %


In [44]:
print('Classification Report :','\n',metrics.classification_report(y_test, Pred_y))

Classification Report : 
               precision    recall  f1-score   support

           1       0.38      0.57      0.45        51
           2       0.45      0.30      0.36        44
           3       0.36      0.39      0.37        54
           4       0.34      0.24      0.28        51

    accuracy                           0.38       200
   macro avg       0.38      0.37      0.37       200
weighted avg       0.38      0.38      0.37       200

