# Practical - 20

### Applying K-NN Algorithm on Wine Dataset and finding the accuracy of the model.

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.metrics import confusion_matrix
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score
from sklearn.metrics import classification_report
from sklearn import tree
from sklearn import preprocessing
from sklearn.datasets import load_wine

In [2]:
import sklearn.datasets as data
wine_data = load_wine()
dataset = pd.DataFrame(wine_data.data)
print("Features Name : ", wine_data.feature_names)
print("Target Name : ", wine_data.target_names)
print("Dataset Length : ", len(dataset))
print("Dataset Shape : ", dataset.shape)
dataset.head()

Features Name :  ['alcohol', 'malic_acid', 'ash', 'alcalinity_of_ash', 'magnesium', 'total_phenols', 'flavanoids', 'nonflavanoid_phenols', 'proanthocyanins', 'color_intensity', 'hue', 'od280/od315_of_diluted_wines', 'proline']
Target Name :  ['class_0' 'class_1' 'class_2']
Dataset Length :  178
Dataset Shape :  (178, 13)


0     1     2     3      4     5     6     7     8     9     10    11  \
0  14.23  1.71  2.43  15.6  127.0  2.80  3.06  0.28  2.29  5.64  1.04  3.92   
1  13.20  1.78  2.14  11.2  100.0  2.65  2.76  0.26  1.28  4.38  1.05  3.40   
2  13.16  2.36  2.67  18.6  101.0  2.80  3.24  0.30  2.81  5.68  1.03  3.17   
3  14.37  1.95  2.50  16.8  113.0  3.85  3.49  0.24  2.18  7.80  0.86  3.45   
4  13.24  2.59  2.87  21.0  118.0  2.80  2.69  0.39  1.82  4.32  1.04  2.93   

       12  
0  1065.0  
1  1050.0  
2  1185.0  
3  1480.0  
4   735.0

In [3]:
dataset.describe()

0           1           2           3           4           5   \
count  178.000000  178.000000  178.000000  178.000000  178.000000  178.000000   
mean    13.000618    2.336348    2.366517   19.494944   99.741573    2.295112   
std      0.811827    1.117146    0.274344    3.339564   14.282484    0.625851   
min     11.030000    0.740000    1.360000   10.600000   70.000000    0.980000   
25%     12.362500    1.602500    2.210000   17.200000   88.000000    1.742500   
50%     13.050000    1.865000    2.360000   19.500000   98.000000    2.355000   
75%     13.677500    3.082500    2.557500   21.500000  107.000000    2.800000   
max     14.830000    5.800000    3.230000   30.000000  162.000000    3.880000   

               6           7           8           9           10          11  \
count  178.000000  178.000000  178.000000  178.000000  178.000000  178.000000   
mean     2.029270    0.361854    1.590899    5.058090    0.957449    2.611685   
std      0.998859    0.124453    0.572359    2.318286    0.228572    0.709990   
min      0.340000    0.130000    0.410000    1.280000    0.480000    1.270000   
25%      1.205000    0.270000    1.250000    3.220000    0.782500    1.937500   
50%      2.135000    0.340000    1.555000    4.690000    0.965000    2.780000   
75%      2.875000    0.437500    1.950000    6.200000    1.120000    3.170000   
max      5.080000    0.660000    3.580000   13.000000    1.710000    4.000000   

                12  
count   178.000000  
mean    746.893258  
std     314.907474  
min     278.000000  
25%     500.500000  
50%     673.500000  
75%     985.000000  
max    1680.000000

In [4]:
x = dataset.values[:, 0:13]
y = wine_data.target
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.25, random_state = 2)

In [5]:
x = preprocessing.StandardScaler().fit(x).transform(x.astype(float)) #Scaling fitting and transforming in single step
# in this step we are using anonymous objects. linking objects without makig them refer is called anonymous objects
x[0:5]

array([[ 1.51861254, -0.5622498 ,  0.23205254, -1.16959318,  1.91390522,
         0.80899739,  1.03481896, -0.65956311,  1.22488398,  0.25171685,
         0.36217728,  1.84791957,  1.01300893],
       [ 0.24628963, -0.49941338, -0.82799632, -2.49084714,  0.01814502,
         0.56864766,  0.73362894, -0.82071924, -0.54472099, -0.29332133,
         0.40605066,  1.1134493 ,  0.96524152],
       [ 0.19687903,  0.02123125,  1.10933436, -0.2687382 ,  0.08835836,
         0.80899739,  1.21553297, -0.49840699,  2.13596773,  0.26901965,
         0.31830389,  0.78858745,  1.39514818],
       [ 1.69154964, -0.34681064,  0.4879264 , -0.80925118,  0.93091845,
         2.49144552,  1.46652465, -0.98187536,  1.03215473,  1.18606801,
        -0.42754369,  1.18407144,  2.33457383],
       [ 0.29570023,  0.22769377,  1.84040254,  0.45194578,  1.28198515,
         0.80899739,  0.66335127,  0.22679555,  0.40140444, -0.31927553,
         0.36217728,  0.44960118, -0.03787401]])

In [6]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn import metrics
k = 4
knnClassifier = KNeighborsClassifier(n_neighbors = k, metric = "minkowski", p = 2).fit(x_train, y_train)

In [7]:
y_pred = knnClassifier.predict(x_test)
print("Accuracy of model at K = 4 is :", metrics.accuracy_score(y_test, y_pred))

Accuracy of model at K = 4 is : 0.7111111111111111


In [8]:
k = 5
knnClassifier = KNeighborsClassifier(n_neighbors = k, metric = "minkowski", p = 2).fit(x_train, y_train)
y_pred = knnClassifier.predict(x_test)
print("Accuracy of model at K = 5 is :", metrics.accuracy_score(y_test, y_pred))

Accuracy of model at K = 5 is : 0.6888888888888889


In [9]:
k = 6
knnClassifier = KNeighborsClassifier(n_neighbors = k, metric = "minkowski", p = 2).fit(x_train, y_train)
y_pred = knnClassifier.predict(x_test)
print("Accuracy of model at K = 6 is :", metrics.accuracy_score(y_test, y_pred))

Accuracy of model at K = 6 is : 0.6888888888888889


In [10]:
k = 7
knnClassifier = KNeighborsClassifier(n_neighbors = k, metric = "minkowski", p = 2).fit(x_train, y_train)
y_pred = knnClassifier.predict(x_test)
print("Accuracy of model at K = 7 is :", metrics.accuracy_score(y_test, y_pred))

Accuracy of model at K = 7 is : 0.7111111111111111


In [11]:
k = 20
knnClassifier = KNeighborsClassifier(n_neighbors = k, metric = "minkowski", p = 2).fit(x_train, y_train)
y_pred = knnClassifier.predict(x_test)
print("Accuracy of model at K = 20 is :", metrics.accuracy_score(y_test, y_pred))

Accuracy of model at K = 20 is : 0.7777777777777778


In [12]:
k = 25
knnClassifier = KNeighborsClassifier(n_neighbors = k, metric = "minkowski", p = 2).fit(x_train, y_train)
y_pred = knnClassifier.predict(x_test)
print("Accuracy of model at K = 25 is :", metrics.accuracy_score(y_test, y_pred))

Accuracy of model at K = 25 is : 0.7777777777777778


In [13]:
k = 30
knnClassifier = KNeighborsClassifier(n_neighbors = k, metric = "minkowski", p = 2).fit(x_train, y_train)
y_pred = knnClassifier.predict(x_test)
print("Accuracy of model at K = 30 is :", metrics.accuracy_score(y_test, y_pred))

Accuracy of model at K = 30 is : 0.7333333333333333


In [14]:
k = 14
knnClassifier = KNeighborsClassifier(n_neighbors = k, metric = "minkowski", p = 2).fit(x_train, y_train)
y_pred = knnClassifier.predict(x_test)
print("Accuracy of model at K = 7 is :", metrics.accuracy_score(y_test, y_pred))

Accuracy of model at K = 7 is : 0.7333333333333333


In [15]:
k = 20
knnClassifier = KNeighborsClassifier(n_neighbors = k, metric = "minkowski", p = 2).fit(x_train, y_train)
y_pred = knnClassifier.predict(x_test)
print("Accuracy of model at K = 20 is :", metrics.accuracy_score(y_test, y_pred))
confusion_matrix = metrics.confusion_matrix(y_test,y_pred) 
print(confusion_matrix)

Accuracy of model at K = 20 is : 0.7777777777777778
[[19  0  0]
 [ 0  8  5]
 [ 2  3  8]]


In [16]:
print(metrics.classification_report(y_test, y_pred))
print("Accuracy of model at K = 20 is :", metrics.accuracy_score(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.90      1.00      0.95        19
           1       0.73      0.62      0.67        13
           2       0.62      0.62      0.62        13

    accuracy                           0.78        45
   macro avg       0.75      0.74      0.74        45
weighted avg       0.77      0.78      0.77        45

Accuracy of model at K = 20 is : 0.7777777777777778
